version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      APP_ENV: dev
      APP_SECRET: 'your_secret_here'
      DATABASE_URL: "mysql://root:password@db:3306/barber"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
      MAILER_DSN: "null://null"
    depends_on:
      - db

  db:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: barber
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
